# Generated by Django 5.1 on 2024-08-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tarefa', models.CharField(max_length=100)),
                ('status_tarefa', models.BooleanField(default=False)),
                ('descricao_tarefa', models.TextField(blank=True)),
                ('prioridade_tarefa', models.BooleanField(default=False)),
            ],
        ),
    ]
