# Generated by Django 5.1 on 2024-09-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestortarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='prioridade_tarefa',
        ),
    ]
